spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/implement
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Atualiza o banco de dados automaticamente
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Mostra as queries SQL geradas no log
